development:
  adapter: postgresql
  encoding: unicode
  database: queue_classic_demo_development
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: queue_classic_demo_production
  pool: 5
  password:
